version: '3.8'
services:
  anaconda:
    container_name: anaconda
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src:/opt/notebooks/
    command: /bin/bash -c "/opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]